name: 'Scora Cleaner GCR'
author: Guilherme Morone <guilherme.morone@oncase.com.br>
description: 'Clear untagged images at container registry'
inputs:
  project_id:
    description: 'The id of your GCP project'
    required: true
  image_name:
    description: 'The name of the image you want to clean'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_id }}
    - ${{ inputs.image_name }}
